version: '3.8'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_START_RPC=true
    ports:
      - "9042:9042"   # CQL ポート
    volumes:
      - ./cassandra-data:/var/lib/cassandra
    networks:
      - cassandra-net

  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
    networks:
      - app-net

  front:
    build: ./front
    container_name: front
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-net

networks:
  cassandra-net:
    driver: bridge
